### ISSUE TITLE
gb vendor: deleting a "parent" package deletes nested packages from vendor dir.

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#299]
```
$ gb vendor fetch golang.org/x/sys/windows/registry
$ gb vendor fetch golang.org/x/sys/windows
$ gb vendor delete golang.org/x/sys/windows
```

Note that package `golang.org/x/sys/windows/registry` no longer exists in vendor dir, but is still registered in manifest.

Neither of these two packages depends on the other.

Trying to delete `golang.org/x/sys/windows/registry` now panics.

```
$ gb vendor delete golang.org/x/sys/windows/registry
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x487951]

goroutine 1 [running]:
github.com/constabulary/gb/vendor.func┬╖004(0xc082009fc0, 0x3f, 0x0, 0x0, 0x3926f0, 0xc0820b4f00, 0x0, 0x0)
        C:/gopath/src/github.com/constabulary/gb/vendor/remove.go:15 +0x41
path/filepath.Walk(0xc082009fc0, 0x3f, 0x937720, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:392 +0xbd
github.com/constabulary/gb/vendor.RemoveAll(0xc082009fc0, 0x3f, 0x0, 0x0)
        C:/gopath/src/github.com/constabulary/gb/vendor/remove.go:20 +0x57
main.func┬╖001(0xc08200c3f0, 0xc082003f10, 0x1, 0x1, 0x0, 0x0)
        C:/gopath/src/github.com/constabulary/gb/cmd/gb-vendor/delete.go:67 +0x6cb
main.main()
        C:/gopath/src/github.com/constabulary/gb/cmd/gb-vendor/main.go:84 +0xaf0
```

**Comment by davecheney** [comment]
Damnit. It's specifically not supposed to do this.
