### ISSUE TITLE
`gb plugin` panics

### ISSUE THREAD

**Issue by henrikhodne** [constabulary/gb#329]
If I run a plain `gb plugin` I get this panic:

```
$ gb plugin                               
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.func·005(0xc20805c180, 0xc20800a010, 0x0, 0x0, 0x0, 0x0)
	/path/to/gopath/src/github.com/constabulary/gb/cmd/gb/plugin.go:61 +0x175
main.main()
	/path/to/gopath/src/github.com/constabulary/gb/cmd/gb/main.go:66 +0x48e

goroutine 5 [runnable]:
text/template/parse.lexText(0xc20804c200, 0x8fd3e8)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20804c200)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac
```

The version I currently have installed is d4f8e79d34e93d18fb16b54e041516f77c4471b7.

**Comment by davecheney** [comment]
Sorry, this was fixed once before, and i'll fix it again.

FWIW, that command doesn't do anything by itself, so you're not missing out on much.
