### ISSUE TITLE
Multiple test failures on Windows

### ISSUE THREAD

**Issue by inconshreveable** [constabulary/gb#384]
OS: Win7 x64
Go: 1.5.1

Pulling this out of https://github.com/constabulary/gb/pull/377 per request.

```
C:\Users\alan\gopath\src\github.com\constabulary\gb>go test -short github.com/co
nstabulary/gb/...
a
a
b
a
d.v1
c
d.v1
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
notestfiles
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
--- FAIL: TestBuild (0.62s)
        build_test.go:74: ctx.Build(cgomain): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb281314287\cgomain\_c
go -importpath cgomain -- -I C:\Users\alan\AppData\Local\Temp\gb281314287\cgomai
n\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgoma
in main.go: exit status 2
        build_test.go:74: ctx.Build(cgotest): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb997494402\cgotest\_c
go -importpath cgotest -- -I C:\Users\alan\AppData\Local\Temp\gb997494402\cgotes
t\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgote
st basic.go: exit status 2
        build_test.go:74: ctx.Build(cgoonlynotest): want <nil>, got # C:\Go\pkg\
tool\windows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb557978884\cgoo
nly\_cgo -importpath cgoonlynotest -- -I C:\Users\alan\AppData\Local\Temp\gb5579
78884\cgoonly\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testda
ta\src\cgoonlynotest cgoonly.go: exit status 2
        build_test.go:74: ctx.Build(cppmain): want <nil>, got # C:\Go\pkg\tool\w
indows_amd64\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb119974520\cppmain\_c
go -importpath cppmain -- -I C:\Users\alan\AppData\Local\Temp\gb119974520\cppmai
n\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cppma
in main.go: exit status 2
a
a
b
a
d.v1
c
d.v1
a
b
--- FAIL: TestPackageBinfile (0.00s)
        package_test.go:68: (b).Binfile(): want C:\Users\alan\gopath\src\github.
com\constabulary\gb\testdata\bin\b, got C:\Users\alan\gopath\src\github.com\cons
tabulary\gb\testdata\bin\b.exe
FAIL
FAIL    github.com/constabulary/gb      1.409s
*** Test killed: ran too long (10m0s).
FAIL    github.com/constabulary/gb/cmd  600.170s
ok      github.com/constabulary/gb/cmd/gb       0.100s
?       github.com/constabulary/gb/cmd/gb-vendor        [no test files]
?       github.com/constabulary/gb/log  [no test files]
ok      github.com/constabulary/gb/vendor       0.245s
```

**Comment by inconshreveable** [comment]
Note that in addition to the two failing tests that the tests for gb/cmd also never complete and timeout.

**Comment by davecheney** [comment]
What gcc do you have on your test machine ?

**Comment by inconshreveable** [comment]
```
C:\Users\alan\gopath\src\github.com\constabulary\gb>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.8.1/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.8.1/configure --prefix=/mingw --host=mingw32 --build=m
ingw32 --without-pic --enable-shared --enable-static --with-gnu-ld --enable-lto
--enable-libssp --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++
,ada --disable-sjlj-exceptions --with-dwarf2 --disable-win32-registry --enable-l
ibstdcxx-debug --enable-version-specific-runtime-libs --with-gmp=/usr/src/pkg/gm
p-5.1.2-1-mingw32-src/bld --with-mpc=/usr/src/pkg/mpc-1.0.1-1-mingw32-src/bld --
with-mpfr= --with-system-zlib --with-gnu-as --enable-decimal-float=yes --enable-
libgomp --enable-threads --with-libiconv-prefix=/mingw32 --with-libintl-prefix=/
mingw --disable-bootstrap LDFLAGS=-s CFLAGS=-D_USE_32BIT_TIME_T
Thread model: win32
gcc version 4.8.1 (GCC)
```

**Comment by davecheney** [comment]
What GOARCH value are you using on that vm ? It looks like that is a 32bit
gcc but gb is treating it like amd64

**Comment by inconshreveable** [comment]
not entirely sure what you're asking here? there's not GOARCH environment variable set, so it's using the OS default (amd64). running the tests with GOARCH=386 produces additional tests errors:

```
C:\Users\alan\gopath\src\github.com\constabulary\gb>set GOARCH=386

C:\Users\alan\gopath\src\github.com\constabulary\gb>go test -short github.com/co
nstabulary/gb/...
a
a
a
d.v1
d.v1
notestfiles
--- FAIL: TestBuild (0.03s)
        build_test.go:74: ctx.Build(a): want <nil>, got exec: "C:\\Go\\pkg\\tool
\\windows_386\\compile.exe": file does not exist
        build_test.go:74: ctx.Build(b): want <nil>, got exec: "C:\\Go\\pkg\\tool
\\windows_386\\compile.exe": file does not exist
        build_test.go:74: ctx.Build(c): want <nil>, got exec: "C:\\Go\\pkg\\tool
\\windows_386\\compile.exe": file does not exist
        build_test.go:74: ctx.Build(d.v1): want <nil>, got exec: "C:\\Go\\pkg\\t
ool\\windows_386\\compile.exe": file does not exist
        build_test.go:74: ctx.Build(cgomain): want <nil>, got # C:\Go\pkg\tool\w
indows_386\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb642678559\cgomain\_cgo
 -importpath cgomain -- -I C:\Users\alan\AppData\Local\Temp\gb642678559\cgomain\
_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgomain
 main.go: exec: "C:\\Go\\pkg\\tool\\windows_386\\cgo": file does not exist
        build_test.go:74: ctx.Build(cgotest): want <nil>, got # C:\Go\pkg\tool\w
indows_386\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb116975602\cgotest\_cgo
 -importpath cgotest -- -I C:\Users\alan\AppData\Local\Temp\gb116975602\cgotest\
_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cgotest
 basic.go: exec: "C:\\Go\\pkg\\tool\\windows_386\\cgo": file does not exist
        build_test.go:74: ctx.Build(notestfiles): want <nil>, got exec: "C:\\Go\
\pkg\\tool\\windows_386\\compile.exe": file does not exist
        build_test.go:74: ctx.Build(cgoonlynotest): want <nil>, got # C:\Go\pkg\
tool\windows_386\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb296190964\cgoonl
y\_cgo -importpath cgoonlynotest -- -I C:\Users\alan\AppData\Local\Temp\gb296190
964\cgoonly\_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata
\src\cgoonlynotest cgoonly.go: exec: "C:\\Go\\pkg\\tool\\windows_386\\cgo": file
 does not exist
        build_test.go:74: ctx.Build(cppmain): want <nil>, got # C:\Go\pkg\tool\w
indows_386\cgo -objdir C:\Users\alan\AppData\Local\Temp\gb922554984\cppmain\_cgo
 -importpath cppmain -- -I C:\Users\alan\AppData\Local\Temp\gb922554984\cppmain\
_cgo -I C:\Users\alan\gopath\src\github.com\constabulary\gb\testdata\src\cppmain
 main.go: exec: "C:\\Go\\pkg\\tool\\windows_386\\cgo": file does not exist
a
a
a
d.v1
--- FAIL: TestExecuteBuildAction (0.01s)
        executor_test.go:53: Execute(build: a): want: <nil>, got exec: "C:\\Go\\
pkg\\tool\\windows_386\\compile.exe": file does not exist
        executor_test.go:53: Execute(build: b): want: <nil>, got exec: "C:\\Go\\
pkg\\tool\\windows_386\\compile.exe": file does not exist
        executor_test.go:53: Execute(build: c): want: <nil>, got exec: "C:\\Go\\
pkg\\tool\\windows_386\\compile.exe": file does not exist
        executor_test.go:53: Execute(build: d.v1): want: <nil>, got exec: "C:\\G
o\\pkg\\tool\\windows_386\\compile.exe": file does not exist
a
--- FAIL: TestStale (0.00s)
        install_test.go:76: exec: "C:\\Go\\pkg\\tool\\windows_386\\compile.exe":
 file does not exist
--- FAIL: TestPackageBinfile (0.00s)
        package_test.go:68: (b).Binfile(): want C:\Users\alan\gopath\src\github.
com\constabulary\gb\testdata\bin\b, got C:\Users\alan\gopath\src\github.com\cons
tabulary\gb\testdata\bin\b.exe
FAIL
FAIL    github.com/constabulary/gb      0.180s
```

**Comment by inconshreveable** [comment]
took a look at this again today, and it was very obviously an issue with having only a 32-bit gcc installed. apologies!

**Comment by davecheney** [comment]
Thanks for confirming, @tianon set up a windows builder and we'll get those
timeout failures fixed up.

**Comment by tianon** [comment]
Oh, this timeout is literally exactly what I just messaged you about.  Hah.
:+1:

This timeout bug is basically the only failing unit test I've got left for
at least this x64 builder. :metal:

**Comment by inconshreveable** [comment]
Awesome. Yeah, just to confirm, it's this timeout bug:

```
C:\Users\alan\gopath>go test -short -timeout=15s github.com\constabulary\gb\...
ok      github.com/constabulary/gb      5.739s
panic: test timed out after 15s

goroutine 12 [running]:
testing.startAlarm.func1()
        c:/go/src/testing/testing.go:703 +0x139
created by time.goFunc
        c:/go/src/time/sleep.go:129 +0x41

goroutine 1 [chan receive]:
testing.RunTests(0x7392b8, 0x812420, 0xb, 0xb, 0xc08202f401)
        c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc082081ef8, 0x5)
        c:/go/src/testing/testing.go:494 +0x77
main.main()
        github.com/constabulary/gb/cmd/_test/_testmain.go:74 +0x11d

goroutine 9 [runnable]:
runtime.Gosched()
        c:/go/src/runtime/proc.go:166 +0x14
path/filepath.Clean(0xc082465ff2, 0x5, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:145 +0x84d
path/filepath.joinNonEmpty(0xc082085c58, 0x2, 0x2, 0x0, 0x0)
        c:/go/src/path/filepath/path_windows.go:126 +0x9d
path/filepath.join(0xc082085c58, 0x2, 0x2, 0x0, 0x0)
        c:/go/src/path/filepath/path_windows.go:115 +0xd9
path/filepath.Join(0xc082085c58, 0x2, 0x2, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:206 +0x48
github.com/constabulary/gb/cmd.FindProjectroot(0xc082465fd0, 0x3, 0x0, 0x0, 0x0,
 0x0)
        C:/Users/alan/gopath/src/github.com/constabulary/gb/cmd/path.go:20 +0x19
1
github.com/constabulary/gb/cmd.TestFindProjectroot(0xc082094120)
        C:/Users/alan/gopath/src/github.com/constabulary/gb/cmd/path_test.go:58
+0x7cd
testing.tRunner(0xc082094120, 0x812450)
        c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
        c:/go/src/testing/testing.go:561 +0x874
FAIL    github.com/constabulary/gb/cmd  15.295s
ok      github.com/constabulary/gb/cmd/gb       0.208s
?       github.com/constabulary/gb/cmd/gb-vendor        [no test files]
?       github.com/constabulary/gb/log  [no test files]
ok      github.com/constabulary/gb/vendor       0.234s
```

**Comment by davecheney** [comment]
Can you change the value of Verbose at the top of the cmd/test_test.go
tests, and try again, that should give some more information.

Also, is the CPU idle or pegged while the test is timing out ?

**Comment by inconshreveable** [comment]
Found it. Offending code is here: https://github.com/constabulary/gb/blob/master/cmd/path.go#L19

```go
	for path != "/" {
		root := filepath.Join(path, "src")
		if _, err := os.Stat(root); err != nil {
```

The root path on windows is not `/`, so it just loops infinitely. Probably best to just keep a record of the last path seen and quit the loop when it doesn't change anymore.

**Comment by davecheney** [comment]
Right. I'll fix that asap. I'm glad it wasn't a logical error in the
executor.

**Comment by tianon** [comment]
Eeek, `testmainpkg.Binfile()+".test"` is a problem too.  Not sure how to solve that one quite yet, but I've got some fixes worked up for other Windows issues though! (including the infinite loop; nice catch @inconshreveable!!)

**Comment by tianon** [comment]
I'm going to reopen this to track "Windows issues" in general until we get this totally put to bed. :+1:

**Comment by tianon** [comment]
I've got a fix for the test that's checking against things like `a.exe.test`, but I'm not sure whether we should really be fixing the compiler to generate `a.test.exe` instead.  I suppose it's probably worth checking what the `go` tool does.
