### ISSUE TITLE
gb vendor update --all fails with runtime error when vendor/src folder is removed

### ISSUE THREAD

**Issue by evgenybf** [constabulary/gb#398]
OS: Win7x64, go1.5

Steps to reproduce:
```shell
mkdir -p goproject/src
cd goproject
gb vendor fetch "github.com/labstack/echo"
rm -rf vendor/src
gb vendor update --all
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4a4d28]

goroutine 1 [running]:
github.com/constabulary/gb/vendor.RemoveAll.func1(0xc0821e9700, 0x39, 0x0, 0x0, 0x3a4c80, 0xc0821f40
f0, 0x0, 0x0)
        C:/Develop/Go/gopath/src/github.com/constabulary/gb/vendor/remove.go:15 +0x38
path/filepath.Walk(0xc0821e9700, 0x39, 0x986dc8, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:394 +0xac
github.com/constabulary/gb/vendor.RemoveAll(0xc0821e9700, 0x39, 0x0, 0x0)
        C:/Develop/Go/gopath/src/github.com/constabulary/gb/vendor/remove.go:20 +0x4a
main.glob.func5(0xc08207e0e0, 0xc082003fa0, 0x0, 0x0, 0x0, 0x0)
        C:/Develop/Go/gopath/src/github.com/constabulary/gb/cmd/gb-vendor/update.go:105 +0xa37
main.main()
        C:/Develop/Go/gopath/src/github.com/constabulary/gb/cmd/gb-vendor/main.go:86 +0xb02
FATAL command "vendor" failed: exit status 2
```

**Comment by davecheney** [comment]
Thanks. Fixing coming right up.

**Comment by evgenybf** [comment]
Thanks!

I would add the following check to the function:
```go
func RemoveAll(path string) error {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
```
and treat the error occurred in the anonymous WalkFunc as warning.
