### ISSUE TITLE
gb not compiling on loongson-3 using gccgo-5 on debian sid

### ISSUE THREAD

**Issue by omac777** [constabulary/gb#584]
root@sunhaiyong:~# go get github.com/constabulary/gb/...
fatal error: libgo built without FFI does not support reflect.Call or runtime.SetFinalizer

goroutine 18 [running]:
runtime_dopanic
	../../../src/libgo/runtime/panic.c:131
runtime_throw
	../../../src/libgo/runtime/panic.c:193
reflect.call
	../../../src/libgo/runtime/go-reflect-call.c:246
runfinq
	../../../src/libgo/runtime/mgc0.c:2538
kickoff
	../../../src/libgo/runtime/proc.c:235
created by runtime_createfing
	../../../src/libgo/runtime/mgc0.c:2572

goroutine 16 [runnable]:
go_build.Import.pN16_go_build.Context
	../../../src/libgo/go/go/build/build.go:742
go_build.ImportDir.pN16_go_build.Context
	../../../src/libgo/go/go/build/build.go:413
main.$nested28
	../../src/gotools/../libgo/go/cmd/go/main.go:569
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:347
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:372
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:372
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:372
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:372
filepath.walk
	../../../src/libgo/go/path/filepath/path.go:372
path_filepath.Walk
	../../../src/libgo/go/path/filepath/path.go:394
main.matchPackages
	../../src/gotools/../libgo/go/cmd/go/main.go:544
main.download
	../../src/gotools/../libgo/go/cmd/go/get.go:194
main.runGet
	../../src/gotools/../libgo/go/cmd/go/get.go:79
main.main
	../../src/gotools/../libgo/go/cmd/go/main.go:163
created by main
	../../../src/libgo/runtime/go-main.c:48

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	../../../src/libgo/go/os/signal/signal_unix.go:25

**Comment by davecheney** [comment]
I am sorry, gb does not support gccgo yet. It's on the list  but no eta at
the moment
